Repository guardrails-ai/guardrails, pull requests merged in 2024-05, with the labels that each got.

#763 Deprecate superfluous read-only properties.
  Makefile
  guardrails/applications/text2sql.py
  guardrails/guard.py
Labels: dependencies, deprecation

#767 Implementing a basic AsyncGuard to logically separate out async calls from Guard() into a new client
  guardrails/__init__.py
  guardrails/async_guard.py
  guardrails/guard.py
  tests/unit_tests/test_async_guard.py
Labels: enhancement, python

#759 0.4.4 dev
  .github/workflows/ci.yml
  docs/examples/bug_free_python_code.ipynb
  docs/examples/check_for_pii.ipynb
  docs/examples/competitors_check.ipynb
  docs/examples/extracting_entities.ipynb
  docs/examples/generate_structured_data.ipynb
  docs/examples/guardrails_with_chat_models.ipynb
  docs/examples/input_validation.ipynb
  guardrails/__init__.py
  guardrails/async_guard.py
  guardrails/classes/credentials.py
  guardrails/cli/configure.py
  guardrails/cli/hub/__init__.py
  guardrails/cli/hub/install.py
  guardrails/cli/hub/uninstall.py
  guardrails/cli/hub/utils.py
  guardrails/cli/server/hub_client.py
  guardrails/guard.py
  poetry.lock
  pyproject.toml
  tests/unit_tests/classes/test_credentials.py
  tests/unit_tests/cli/hub/test_install.py
  tests/unit_tests/cli/hub/test_uninstall.py
  tests/unit_tests/cli/test_configure.py
  tests/unit_tests/test_async_guard.py
Labels: release
