Repository guardrails-ai/guardrails, pull requests merged in 2024-06, with the labels that each got.

#801 Fix: Small typo fixes for 'gudardrails' and for variable replacement.
  docs-graveyard/getting_started.md
  docs/guardrails_ai/getting_started.md
  docs/hub/how_to_guides/input_validation.md
Labels: documentation

#813 make guard(llm_api optional
  guardrails/async_guard.py
  guardrails/guard.py
  guardrails/llm_providers.py
  guardrails/run/async_runner.py
  guardrails/run/runner.py
  tests/integration_tests/test_guard.py
Labels: enhancement, feature

#815 Adding functionality for validator hub passthrough of hosted ML endpoints
  guardrails/classes/credentials.py
  guardrails/cli/configure.py
  guardrails/cli/hub/install.py
  guardrails/cli/server/module_manifest.py
  guardrails/hub_token/token.py
  guardrails/remote_inference/__init__.py
  guardrails/remote_inference/remote_inference.py
  guardrails/telemetry/__init__.py
  guardrails/telemetry/telemetry.py
  guardrails/validator_base.py
  tests/unit_tests/cli/hub/test_install.py
  tests/unit_tests/cli/test_configure.py
Labels: enhancement
